'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class IdiomaComun
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DipuAlba.Seres.Idioma.IdiomaComun", GetType(IdiomaComun).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} no es válido.
        '''</summary>
        Public Shared ReadOnly Property _0noEsValido() As String
            Get
                Return ResourceManager.GetString("0noEsValido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} no puede ser vacío.
        '''</summary>
        Public Shared ReadOnly Property _0NoPuedeSerVacio() As String
            Get
                Return ResourceManager.GetString("0NoPuedeSerVacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Abreviatura.
        '''</summary>
        Public Shared ReadOnly Property Abreviatura() As String
            Get
                Return ResourceManager.GetString("Abreviatura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accesibilidad.
        '''</summary>
        Public Shared ReadOnly Property Accesibilidad() As String
            Get
                Return ResourceManager.GetString("Accesibilidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acceso no permitido.
        '''</summary>
        Public Shared ReadOnly Property AccesoNoPermitido() As String
            Get
                Return ResourceManager.GetString("AccesoNoPermitido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aceptar.
        '''</summary>
        Public Shared ReadOnly Property Aceptar() As String
            Get
                Return ResourceManager.GetString("Aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actual.
        '''</summary>
        Public Shared ReadOnly Property Actual() As String
            Get
                Return ResourceManager.GetString("Actual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administración.
        '''</summary>
        Public Shared ReadOnly Property Administracion() As String
            Get
                Return ResourceManager.GetString("Administracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administración del Estado.
        '''</summary>
        Public Shared ReadOnly Property AdministracionDelEstado() As String
            Get
                Return ResourceManager.GetString("AdministracionDelEstado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alta.
        '''</summary>
        Public Shared ReadOnly Property Alta() As String
            Get
                Return ResourceManager.GetString("Alta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ámbito.
        '''</summary>
        Public Shared ReadOnly Property Ambito() As String
            Get
                Return ResourceManager.GetString("Ambito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ampliar vista de edición.
        '''</summary>
        Public Shared ReadOnly Property AmpliarVistaDeEdicion() As String
            Get
                Return ResourceManager.GetString("AmpliarVistaDeEdicion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añadir.
        '''</summary>
        Public Shared ReadOnly Property Anadir() As String
            Get
                Return ResourceManager.GetString("Anadir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añadir correo.
        '''</summary>
        Public Shared ReadOnly Property AnadirCorreo() As String
            Get
                Return ResourceManager.GetString("AnadirCorreo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añadir Dirección Electrónica Habilitada.
        '''</summary>
        Public Shared ReadOnly Property AnadirDeh() As String
            Get
                Return ResourceManager.GetString("AnadirDeh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añadir domicilio.
        '''</summary>
        Public Shared ReadOnly Property AnadirDomicilio() As String
            Get
                Return ResourceManager.GetString("AnadirDomicilio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añadir representante.
        '''</summary>
        Public Shared ReadOnly Property AnadirRepresentante() As String
            Get
                Return ResourceManager.GetString("AnadirRepresentante", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añadir teléfono.
        '''</summary>
        Public Shared ReadOnly Property AnadirTelefono() As String
            Get
                Return ResourceManager.GetString("AnadirTelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anterior.
        '''</summary>
        Public Shared ReadOnly Property Anterior() As String
            Get
                Return ResourceManager.GetString("Anterior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Antigua.
        '''</summary>
        Public Shared ReadOnly Property Antigua() As String
            Get
                Return ResourceManager.GetString("Antigua", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Antiguo.
        '''</summary>
        Public Shared ReadOnly Property Antiguo() As String
            Get
                Return ResourceManager.GetString("Antiguo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Año.
        '''</summary>
        Public Shared ReadOnly Property Anyo() As String
            Get
                Return ResourceManager.GetString("Anyo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primer apellido.
        '''</summary>
        Public Shared ReadOnly Property Apellido1() As String
            Get
                Return ResourceManager.GetString("Apellido1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segundo apellido.
        '''</summary>
        Public Shared ReadOnly Property Apellido2() As String
            Get
                Return ResourceManager.GetString("Apellido2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apellidos.
        '''</summary>
        Public Shared ReadOnly Property Apellidos() As String
            Get
                Return ResourceManager.GetString("Apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asistencia al ciudadano en trámites de la sede.
        '''</summary>
        Public Shared ReadOnly Property AsistenciaCiudadana() As String
            Get
                Return ResourceManager.GetString("AsistenciaCiudadana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Asistencia en trámites.
        '''</summary>
        Public Shared ReadOnly Property AsistenciaEnTramites() As String
            Get
                Return ResourceManager.GetString("AsistenciaEnTramites", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autenticarse.
        '''</summary>
        Public Shared ReadOnly Property Autenticarse() As String
            Get
                Return ResourceManager.GetString("Autenticarse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automático.
        '''</summary>
        Public Shared ReadOnly Property Automático() As String
            Get
                Return ResourceManager.GetString("Automático", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autor.
        '''</summary>
        Public Shared ReadOnly Property Autor() As String
            Get
                Return ResourceManager.GetString("Autor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aviso.
        '''</summary>
        Public Shared ReadOnly Property Aviso() As String
            Get
                Return ResourceManager.GetString("Aviso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVISO:.
        '''</summary>
        Public Shared ReadOnly Property AVISODosPuntos() As String
            Get
                Return ResourceManager.GetString("AVISODosPuntos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aviso legal.
        '''</summary>
        Public Shared ReadOnly Property AvisoLegal() As String
            Get
                Return ResourceManager.GetString("AvisoLegal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bienvenida.
        '''</summary>
        Public Shared ReadOnly Property Bienvenida() As String
            Get
                Return ResourceManager.GetString("Bienvenida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bloqueado.
        '''</summary>
        Public Shared ReadOnly Property Bloqueado() As String
            Get
                Return ResourceManager.GetString("Bloqueado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscador calle.
        '''</summary>
        Public Shared ReadOnly Property BuscadorCalle() As String
            Get
                Return ResourceManager.GetString("BuscadorCalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar.
        '''</summary>
        Public Shared ReadOnly Property Buscar() As String
            Get
                Return ResourceManager.GetString("Buscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar plantilla....
        '''</summary>
        Public Shared ReadOnly Property BuscarPlantilla() As String
            Get
                Return ResourceManager.GetString("BuscarPlantilla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar por código, nombre o NIF.
        '''</summary>
        Public Shared ReadOnly Property BuscarPorCodigoNombreNif() As String
            Get
                Return ResourceManager.GetString("BuscarPorCodigoNombreNif", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Búsqueda avanzada.
        '''</summary>
        Public Shared ReadOnly Property BusquedaAvanzada() As String
            Get
                Return ResourceManager.GetString("BusquedaAvanzada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Búsqueda de ciudadanos.
        '''</summary>
        Public Shared ReadOnly Property BusquedaDeCiudadanos() As String
            Get
                Return ResourceManager.GetString("BusquedaDeCiudadanos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Caducidad.
        '''</summary>
        Public Shared ReadOnly Property Caducidad() As String
            Get
                Return ResourceManager.GetString("Caducidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelar.
        '''</summary>
        Public Shared ReadOnly Property Cancelar() As String
            Get
                Return ResourceManager.GetString("Cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargando….
        '''</summary>
        Public Shared ReadOnly Property Cargando() As String
            Get
                Return ResourceManager.GetString("Cargando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Causa.
        '''</summary>
        Public Shared ReadOnly Property Causa() As String
            Get
                Return ResourceManager.GetString("Causa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cerrar.
        '''</summary>
        Public Shared ReadOnly Property Cerrar() As String
            Get
                Return ResourceManager.GetString("Cerrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cerrar sesión.
        '''</summary>
        Public Shared ReadOnly Property CerrarSesion() As String
            Get
                Return ResourceManager.GetString("CerrarSesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ciudadano.
        '''</summary>
        Public Shared ReadOnly Property Ciudadano() As String
            Get
                Return ResourceManager.GetString("Ciudadano", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ciudadanos.
        '''</summary>
        Public Shared ReadOnly Property Ciudadanos() As String
            Get
                Return ResourceManager.GetString("Ciudadanos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clase.
        '''</summary>
        Public Shared ReadOnly Property Clase() As String
            Get
                Return ResourceManager.GetString("Clase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código país.
        '''</summary>
        Public Shared ReadOnly Property CodigoPais() As String
            Get
                Return ResourceManager.GetString("CodigoPais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código postal.
        '''</summary>
        Public Shared ReadOnly Property CodigoPostal() As String
            Get
                Return ResourceManager.GetString("CodigoPostal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código representante.
        '''</summary>
        Public Shared ReadOnly Property CodigoRepresentante() As String
            Get
                Return ResourceManager.GetString("CodigoRepresentante", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comparar ciudadanos.
        '''</summary>
        Public Shared ReadOnly Property CompararCiudadanos() As String
            Get
                Return ResourceManager.GetString("CompararCiudadanos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comparar y unificar ciudadano.
        '''</summary>
        Public Shared ReadOnly Property CompararYUnificarCiudadano() As String
            Get
                Return ResourceManager.GetString("CompararYUnificarCiudadano", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compruebe que ha cumplimentado los siguientes campos.
        '''</summary>
        Public Shared ReadOnly Property CompruebeQueHaRellenadoLosSiguientesCampos() As String
            Get
                Return ResourceManager.GetString("CompruebeQueHaRellenadoLosSiguientesCampos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comunidad autónoma.
        '''</summary>
        Public Shared ReadOnly Property ComunidadAutonoma() As String
            Get
                Return ResourceManager.GetString("ComunidadAutonoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuración.
        '''</summary>
        Public Shared ReadOnly Property Configuracion() As String
            Get
                Return ResourceManager.GetString("Configuracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmación.
        '''</summary>
        Public Shared ReadOnly Property Confirmacion() As String
            Get
                Return ResourceManager.GetString("Confirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmar.
        '''</summary>
        Public Shared ReadOnly Property Confirmar() As String
            Get
                Return ResourceManager.GetString("Confirmar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirmar unificación.
        '''</summary>
        Public Shared ReadOnly Property ConfirmarUnificacion() As String
            Get
                Return ResourceManager.GetString("ConfirmarUnificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contacto.
        '''</summary>
        Public Shared ReadOnly Property Contacto() As String
            Get
                Return ResourceManager.GetString("Contacto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contiene.
        '''</summary>
        Public Shared ReadOnly Property Contiene() As String
            Get
                Return ResourceManager.GetString("Contiene", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copia de.
        '''</summary>
        Public Shared ReadOnly Property CopiaDe() As String
            Get
                Return ResourceManager.GetString("CopiaDe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copiar.
        '''</summary>
        Public Shared ReadOnly Property Copiar() As String
            Get
                Return ResourceManager.GetString("Copiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correcto.
        '''</summary>
        Public Shared ReadOnly Property Correcto() As String
            Get
                Return ResourceManager.GetString("Correcto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Corregir.
        '''</summary>
        Public Shared ReadOnly Property Corregir() As String
            Get
                Return ResourceManager.GetString("Corregir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correo electrónico.
        '''</summary>
        Public Shared ReadOnly Property CorreoElectronico() As String
            Get
                Return ResourceManager.GetString("CorreoElectronico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correos electrónicos.
        '''</summary>
        Public Shared ReadOnly Property CorreosElectronicos() As String
            Get
                Return ResourceManager.GetString("CorreosElectronicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Código Seguro de Validación (CSV).
        '''</summary>
        Public Shared ReadOnly Property CSVLargo() As String
            Get
                Return ResourceManager.GetString("CSVLargo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cualquiera.
        '''</summary>
        Public Shared ReadOnly Property Cualquiera() As String
            Get
                Return ResourceManager.GetString("Cualquiera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe existir al menos uno.
        '''</summary>
        Public Shared ReadOnly Property DebeExistirAlMenosUno() As String
            Get
                Return ResourceManager.GetString("DebeExistirAlMenosUno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe haber, al menos, uno..
        '''</summary>
        Public Shared ReadOnly Property DebeHaberAlMenosUno() As String
            Get
                Return ResourceManager.GetString("DebeHaberAlMenosUno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe ser vacío.
        '''</summary>
        Public Shared ReadOnly Property DebeSerVacio() As String
            Get
                Return ResourceManager.GetString("DebeSerVacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe tener formato {0}.
        '''</summary>
        Public Shared ReadOnly Property DebeTenerFormato0() As String
            Get
                Return ResourceManager.GetString("DebeTenerFormato0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Direcciones electrónicas habilitadas.
        '''</summary>
        Public Shared ReadOnly Property Dehs() As String
            Get
                Return ResourceManager.GetString("Dehs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Demasiado corto.
        '''</summary>
        Public Shared ReadOnly Property DemasiadoCorto() As String
            Get
                Return ResourceManager.GetString("DemasiadoCorto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descargado.
        '''</summary>
        Public Shared ReadOnly Property Descargado() As String
            Get
                Return ResourceManager.GetString("Descargado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descargando.
        '''</summary>
        Public Shared ReadOnly Property Descargando() As String
            Get
                Return ResourceManager.GetString("Descargando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descargar.
        '''</summary>
        Public Shared ReadOnly Property Descargar() As String
            Get
                Return ResourceManager.GetString("Descargar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descargar plantilla.
        '''</summary>
        Public Shared ReadOnly Property DescargarPlantilla() As String
            Get
                Return ResourceManager.GetString("DescargarPlantilla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desconocido.
        '''</summary>
        Public Shared ReadOnly Property Desconocido() As String
            Get
                Return ResourceManager.GetString("Desconocido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descripción.
        '''</summary>
        Public Shared ReadOnly Property Descripcion() As String
            Get
                Return ResourceManager.GetString("Descripcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descripción de la remesa.
        '''</summary>
        Public Shared ReadOnly Property DescripcionDeLaRemesa() As String
            Get
                Return ResourceManager.GetString("DescripcionDeLaRemesa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desde.
        '''</summary>
        Public Shared ReadOnly Property Desde() As String
            Get
                Return ResourceManager.GetString("Desde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deshabilitar.
        '''</summary>
        Public Shared ReadOnly Property Deshabilitar() As String
            Get
                Return ResourceManager.GetString("Deshabilitar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detalles.
        '''</summary>
        Public Shared ReadOnly Property Detalles() As String
            Get
                Return ResourceManager.GetString("Detalles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección.
        '''</summary>
        Public Shared ReadOnly Property Direccion() As String
            Get
                Return ResourceManager.GetString("Direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección completa.
        '''</summary>
        Public Shared ReadOnly Property DireccionCompleta() As String
            Get
                Return ResourceManager.GetString("DireccionCompleta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección electrónica habilitada.
        '''</summary>
        Public Shared ReadOnly Property DireccionElectronicaHabilitada() As String
            Get
                Return ResourceManager.GetString("DireccionElectronicaHabilitada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dir. electrónica.
        '''</summary>
        Public Shared ReadOnly Property DirElectronica() As String
            Get
                Return ResourceManager.GetString("DirElectronica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to También dispone de estadísticas en.
        '''</summary>
        Public Shared ReadOnly Property DisponeDeEstadisticasEn() As String
            Get
                Return ResourceManager.GetString("DisponeDeEstadisticasEn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to o.
        '''</summary>
        Public Shared ReadOnly Property Disyuncion() As String
            Get
                Return ResourceManager.GetString("Disyuncion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Documento.
        '''</summary>
        Public Shared ReadOnly Property Documento() As String
            Get
                Return ResourceManager.GetString("Documento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Doc. Europeo.
        '''</summary>
        Public Shared ReadOnly Property DocumentoEuropeo() As String
            Get
                Return ResourceManager.GetString("DocumentoEuropeo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Documento (NIF/NIE/CIF/Pasaporte).
        '''</summary>
        Public Shared ReadOnly Property DocumentoNIFNIECIFPasaporte() As String
            Get
                Return ResourceManager.GetString("DocumentoNIFNIECIFPasaporte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Domicilios.
        '''</summary>
        Public Shared ReadOnly Property Domicilios() As String
            Get
                Return ResourceManager.GetString("Domicilios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar.
        '''</summary>
        Public Shared ReadOnly Property Editar() As String
            Get
                Return ResourceManager.GetString("Editar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar ciudadano.
        '''</summary>
        Public Shared ReadOnly Property EditarCiudadano() As String
            Get
                Return ResourceManager.GetString("EditarCiudadano", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ejemplo.
        '''</summary>
        Public Shared ReadOnly Property Ejemplo() As String
            Get
                Return ResourceManager.GetString("Ejemplo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ejercicio.
        '''</summary>
        Public Shared ReadOnly Property Ejercicio() As String
            Get
                Return ResourceManager.GetString("Ejercicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El fichero no es válido.
        '''</summary>
        Public Shared ReadOnly Property ElFicheroNoEsValido() As String
            Get
                Return ResourceManager.GetString("ElFicheroNoEsValido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elija al menos una opción.
        '''</summary>
        Public Shared ReadOnly Property ElijaAlMenosUnaOpcion() As String
            Get
                Return ResourceManager.GetString("ElijaAlMenosUnaOpcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elija una opción.
        '''</summary>
        Public Shared ReadOnly Property ElijaUnaOpcion() As String
            Get
                Return ResourceManager.GetString("ElijaUnaOpcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elija un método para autenticarse.
        '''</summary>
        Public Shared ReadOnly Property ElijaUnMetodoParaAutenticarse() As String
            Get
                Return ResourceManager.GetString("ElijaUnMetodoParaAutenticarse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar.
        '''</summary>
        Public Shared ReadOnly Property Eliminar() As String
            Get
                Return ResourceManager.GetString("Eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario no se ha autenticado.
        '''</summary>
        Public Shared ReadOnly Property ElUsuarioNoEstaLogueado() As String
            Get
                Return ResourceManager.GetString("ElUsuarioNoEstaLogueado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario no tiene perfil en esta entidad.
        '''</summary>
        Public Shared ReadOnly Property ElUsuarioNoTienePerfilEnEstaEntidad() As String
            Get
                Return ResourceManager.GetString("ElUsuarioNoTienePerfilEnEstaEntidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario no tiene roles SERES en esta entidad.
        '''</summary>
        Public Shared ReadOnly Property ElUsuarioNoTieneRolesSeresEnEstaEntidad() As String
            Get
                Return ResourceManager.GetString("ElUsuarioNoTieneRolesSeresEnEstaEntidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Empieza.
        '''</summary>
        Public Shared ReadOnly Property Empieza() As String
            Get
                Return ResourceManager.GetString("Empieza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entidad.
        '''</summary>
        Public Shared ReadOnly Property Entidad() As String
            Get
                Return ResourceManager.GetString("Entidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entidad local.
        '''</summary>
        Public Shared ReadOnly Property EntidadLocal() As String
            Get
                Return ResourceManager.GetString("EntidadLocal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entrada.
        '''</summary>
        Public Shared ReadOnly Property Entrada() As String
            Get
                Return ResourceManager.GetString("Entrada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error renovando token solicitud. Puede que el enlace haya caducado, ya se haya autenticado usando el enlace o lo esté haciendo en otro equipo o navegador donde solicitó la autenticación: {0}.
        '''</summary>
        Public Shared ReadOnly Property ErrorRenovandoToken0() As String
            Get
                Return ResourceManager.GetString("ErrorRenovandoToken0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Es.
        '''</summary>
        Public Shared ReadOnly Property Es() As String
            Get
                Return ResourceManager.GetString("Es", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escalera/Piso/Puerta.
        '''</summary>
        Public Shared ReadOnly Property EscaleraPisoPuerta() As String
            Get
                Return ResourceManager.GetString("EscaleraPisoPuerta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Espere.
        '''</summary>
        Public Shared ReadOnly Property Espere() As String
            Get
                Return ResourceManager.GetString("Espere", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estadísticas.
        '''</summary>
        Public Shared ReadOnly Property Estadisticas() As String
            Get
                Return ResourceManager.GetString("Estadisticas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado.
        '''</summary>
        Public Shared ReadOnly Property Estado() As String
            Get
                Return ResourceManager.GetString("Estado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Etiquetas de búsqueda.
        '''</summary>
        Public Shared ReadOnly Property EtiquetasBusqueda() As String
            Get
                Return ResourceManager.GetString("EtiquetasBusqueda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excluida.
        '''</summary>
        Public Shared ReadOnly Property Excluida() As String
            Get
                Return ResourceManager.GetString("Excluida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Excluido.
        '''</summary>
        Public Shared ReadOnly Property Excluido() As String
            Get
                Return ResourceManager.GetString("Excluido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expediente.
        '''</summary>
        Public Shared ReadOnly Property Expediente() As String
            Get
                Return ResourceManager.GetString("Expediente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exportar.
        '''</summary>
        Public Shared ReadOnly Property Exportar() As String
            Get
                Return ResourceManager.GetString("Exportar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extensión.
        '''</summary>
        Public Shared ReadOnly Property Extension() As String
            Get
                Return ResourceManager.GetString("Extension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extranjero (NIE).
        '''</summary>
        Public Shared ReadOnly Property ExtranjeroNIE() As String
            Get
                Return ResourceManager.GetString("ExtranjeroNIE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha.
        '''</summary>
        Public Shared ReadOnly Property Fecha() As String
            Get
                Return ResourceManager.GetString("Fecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha asignación dirección principal.
        '''</summary>
        Public Shared ReadOnly Property FechaAsignacionDireccionPrincipal() As String
            Get
                Return ResourceManager.GetString("FechaAsignacionDireccionPrincipal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de alta.
        '''</summary>
        Public Shared ReadOnly Property FechaDeAlta() As String
            Get
                Return ResourceManager.GetString("FechaDeAlta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de nacimiento.
        '''</summary>
        Public Shared ReadOnly Property FechaDeNacimiento() As String
            Get
                Return ResourceManager.GetString("FechaDeNacimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha fin dirección principal.
        '''</summary>
        Public Shared ReadOnly Property FechaFinDireccionPrincipal() As String
            Get
                Return ResourceManager.GetString("FechaFinDireccionPrincipal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fechas.
        '''</summary>
        Public Shared ReadOnly Property Fechas() As String
            Get
                Return ResourceManager.GetString("Fechas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de última modificación.
        '''</summary>
        Public Shared ReadOnly Property FechaUltimaModificacion() As String
            Get
                Return ResourceManager.GetString("FechaUltimaModificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feliz año nuevo.
        '''</summary>
        Public Shared ReadOnly Property FelizAnyoNuevo() As String
            Get
                Return ResourceManager.GetString("FelizAnyoNuevo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichero importado correctamente.
        '''</summary>
        Public Shared ReadOnly Property FicheroImportadoCorrectamente() As String
            Get
                Return ResourceManager.GetString("FicheroImportadoCorrectamente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichero validado correctamente.
        '''</summary>
        Public Shared ReadOnly Property FicheroValidadoCorrectamente() As String
            Get
                Return ResourceManager.GetString("FicheroValidadoCorrectamente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filtrar.
        '''</summary>
        Public Shared ReadOnly Property Filtrar() As String
            Get
                Return ResourceManager.GetString("Filtrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Firma biométrica de trámites presentados en la provincia.
        '''</summary>
        Public Shared ReadOnly Property FirmaBiometricaDeTramitesPresentadosEnLaProvincia() As String
            Get
                Return ResourceManager.GetString("FirmaBiometricaDeTramitesPresentadosEnLaProvincia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Firma de instancias.
        '''</summary>
        Public Shared ReadOnly Property FirmaDeInstancias() As String
            Get
                Return ResourceManager.GetString("FirmaDeInstancias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Física (NIF).
        '''</summary>
        Public Shared ReadOnly Property FisicaNIF() As String
            Get
                Return ResourceManager.GetString("FisicaNIF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guardado correctamente.
        '''</summary>
        Public Shared ReadOnly Property GuardadoCorrectamente() As String
            Get
                Return ResourceManager.GetString("GuardadoCorrectamente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guardando información.
        '''</summary>
        Public Shared ReadOnly Property GuardandoInformacion() As String
            Get
                Return ResourceManager.GetString("GuardandoInformacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guardar.
        '''</summary>
        Public Shared ReadOnly Property Guardar() As String
            Get
                Return ResourceManager.GetString("Guardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Habilitado.
        '''</summary>
        Public Shared ReadOnly Property Habilitado() As String
            Get
                Return ResourceManager.GetString("Habilitado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Habilitar.
        '''</summary>
        Public Shared ReadOnly Property Habilitar() As String
            Get
                Return ResourceManager.GetString("Habilitar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hasta.
        '''</summary>
        Public Shared ReadOnly Property Hasta() As String
            Get
                Return ResourceManager.GetString("Hasta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hoja de cálculo.
        '''</summary>
        Public Shared ReadOnly Property HojaDeCalculo() As String
            Get
                Return ResourceManager.GetString("HojaDeCalculo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hora.
        '''</summary>
        Public Shared ReadOnly Property Hora() As String
            Get
                Return ResourceManager.GetString("Hora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Identificador.
        '''</summary>
        Public Shared ReadOnly Property Identificador() As String
            Get
                Return ResourceManager.GetString("Identificador", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Antiguo identificador.
        '''</summary>
        Public Shared ReadOnly Property IdentificadorOld() As String
            Get
                Return ResourceManager.GetString("IdentificadorOld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Idioma.
        '''</summary>
        Public Shared ReadOnly Property Idioma() As String
            Get
                Return ResourceManager.GetString("Idioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferencia de idioma.
        '''</summary>
        Public Shared ReadOnly Property IdiomaPreferenciaComunicacion() As String
            Get
                Return ResourceManager.GetString("IdiomaPreferenciaComunicacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Igual.
        '''</summary>
        Public Shared ReadOnly Property Igual() As String
            Get
                Return ResourceManager.GetString("Igual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importar.
        '''</summary>
        Public Shared ReadOnly Property Importar() As String
            Get
                Return ResourceManager.GetString("Importar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importe.
        '''</summary>
        Public Shared ReadOnly Property Importe() As String
            Get
                Return ResourceManager.GetString("Importe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Índice.
        '''</summary>
        Public Shared ReadOnly Property Indice() As String
            Get
                Return ResourceManager.GetString("Indice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indique un motivo.
        '''</summary>
        Public Shared ReadOnly Property IndiqueUnMotivo() As String
            Get
                Return ResourceManager.GetString("IndiqueUnMotivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inf. adicional.
        '''</summary>
        Public Shared ReadOnly Property InfAdicional() As String
            Get
                Return ResourceManager.GetString("InfAdicional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información.
        '''</summary>
        Public Shared ReadOnly Property Informacion() As String
            Get
                Return ResourceManager.GetString("Informacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información del usuario.
        '''</summary>
        Public Shared ReadOnly Property InformacionDelUsuario() As String
            Get
                Return ResourceManager.GetString("InformacionDelUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iniciando descarga.
        '''</summary>
        Public Shared ReadOnly Property IniciandoDescarga() As String
            Get
                Return ResourceManager.GetString("IniciandoDescarga", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invertir selección.
        '''</summary>
        Public Shared ReadOnly Property InvertirSeleccion() As String
            Get
                Return ResourceManager.GetString("InvertirSeleccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jurídica (CIF).
        '''</summary>
        Public Shared ReadOnly Property JuridicaCIF() As String
            Get
                Return ResourceManager.GetString("JuridicaCIF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Justicia.
        '''</summary>
        Public Shared ReadOnly Property Justicia() As String
            Get
                Return ResourceManager.GetString("Justicia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global.
        '''</summary>
        Public Shared ReadOnly Property LabelGlobal() As String
            Get
                Return ResourceManager.GetString("LabelGlobal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La fecha no puede ser menor de {0}.
        '''</summary>
        Public Shared ReadOnly Property LaFechaNoPuedeSerMenorDe0() As String
            Get
                Return ResourceManager.GetString("LaFechaNoPuedeSerMenorDe0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Limpiar.
        '''</summary>
        Public Shared ReadOnly Property Limpiar() As String
            Get
                Return ResourceManager.GetString("Limpiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Listado de ciudadanos.
        '''</summary>
        Public Shared ReadOnly Property ListadoDeCiudadanos() As String
            Get
                Return ResourceManager.GetString("ListadoDeCiudadanos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mayor.
        '''</summary>
        Public Shared ReadOnly Property Mayor() As String
            Get
                Return ResourceManager.GetString("Mayor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Menor.
        '''</summary>
        Public Shared ReadOnly Property Menor() As String
            Get
                Return ResourceManager.GetString("Menor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Public Shared ReadOnly Property MensajeError() As String
            Get
                Return ResourceManager.GetString("MensajeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificación.
        '''</summary>
        Public Shared ReadOnly Property Modificacion() As String
            Get
                Return ResourceManager.GetString("Modificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostrar accesos.
        '''</summary>
        Public Shared ReadOnly Property MostrarAccesos() As String
            Get
                Return ResourceManager.GetString("MostrarAccesos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostrar historial.
        '''</summary>
        Public Shared ReadOnly Property MostrarHistorial() As String
            Get
                Return ResourceManager.GetString("MostrarHistorial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Municipio.
        '''</summary>
        Public Shared ReadOnly Property Municipio() As String
            Get
                Return ResourceManager.GetString("Municipio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navegar hacia.
        '''</summary>
        Public Shared ReadOnly Property NavegarHacia() As String
            Get
                Return ResourceManager.GetString("NavegarHacia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ninguno.
        '''</summary>
        Public Shared ReadOnly Property Ninguno() As String
            Get
                Return ResourceManager.GetString("Ninguno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Public Shared ReadOnly Property No() As String
            Get
                Return ResourceManager.GetString("No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No es.
        '''</summary>
        Public Shared ReadOnly Property NoEs() As String
            Get
                Return ResourceManager.GetString("NoEs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre.
        '''</summary>
        Public Shared ReadOnly Property Nombre() As String
            Get
                Return ResourceManager.GetString("Nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre completo.
        '''</summary>
        Public Shared ReadOnly Property NombreCompleto() As String
            Get
                Return ResourceManager.GetString("NombreCompleto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre de pila.
        '''</summary>
        Public Shared ReadOnly Property NombreDePila() As String
            Get
                Return ResourceManager.GetString("NombreDePila", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No puede ser vacío.
        '''</summary>
        Public Shared ReadOnly Property NoPuedeSerVacio() As String
            Get
                Return ResourceManager.GetString("NoPuedeSerVacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se corrigió ninguno.
        '''</summary>
        Public Shared ReadOnly Property NoSeCorrigioNinguno() As String
            Get
                Return ResourceManager.GetString("NoSeCorrigioNinguno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se encontraron resultados.
        '''</summary>
        Public Shared ReadOnly Property NoSeEncontraronResultados() As String
            Get
                Return ResourceManager.GetString("NoSeEncontraronResultados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No tiene.
        '''</summary>
        Public Shared ReadOnly Property NoTiene() As String
            Get
                Return ResourceManager.GetString("NoTiene", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notificación electrónica.
        '''</summary>
        Public Shared ReadOnly Property NotificacionElectronica() As String
            Get
                Return ResourceManager.GetString("NotificacionElectronica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nueva.
        '''</summary>
        Public Shared ReadOnly Property Nueva() As String
            Get
                Return ResourceManager.GetString("Nueva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nueva versión disponible.
        '''</summary>
        Public Shared ReadOnly Property NuevaVersion() As String
            Get
                Return ResourceManager.GetString("NuevaVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nuevo.
        '''</summary>
        Public Shared ReadOnly Property Nuevo() As String
            Get
                Return ResourceManager.GetString("Nuevo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número.
        '''</summary>
        Public Shared ReadOnly Property Numero() As String
            Get
                Return ResourceManager.GetString("Numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} filas.
        '''</summary>
        Public Shared ReadOnly Property NumFilas() As String
            Get
                Return ResourceManager.GetString("NumFilas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} filas omitidas.
        '''</summary>
        Public Shared ReadOnly Property NumFilasOmitidas() As String
            Get
                Return ResourceManager.GetString("NumFilasOmitidas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Observaciones.
        '''</summary>
        Public Shared ReadOnly Property Observaciones() As String
            Get
                Return ResourceManager.GetString("Observaciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Obviar.
        '''</summary>
        Public Shared ReadOnly Property Obviar() As String
            Get
                Return ResourceManager.GetString("Obviar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oficina.
        '''</summary>
        Public Shared ReadOnly Property Oficina() As String
            Get
                Return ResourceManager.GetString("Oficina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opciones.
        '''</summary>
        Public Shared ReadOnly Property Opciones() As String
            Get
                Return ResourceManager.GetString("Opciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Orden.
        '''</summary>
        Public Shared ReadOnly Property Orden() As String
            Get
                Return ResourceManager.GetString("Orden", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Origen.
        '''</summary>
        Public Shared ReadOnly Property Origen() As String
            Get
                Return ResourceManager.GetString("Origen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Otros.
        '''</summary>
        Public Shared ReadOnly Property Otros() As String
            Get
                Return ResourceManager.GetString("Otros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Página.
        '''</summary>
        Public Shared ReadOnly Property Pagina() As String
            Get
                Return ResourceManager.GetString("Pagina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to País.
        '''</summary>
        Public Shared ReadOnly Property Pais() As String
            Get
                Return ResourceManager.GetString("Pais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panel de administración.
        '''</summary>
        Public Shared ReadOnly Property PanelAdministracion() As String
            Get
                Return ResourceManager.GetString("PanelAdministracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parcial.
        '''</summary>
        Public Shared ReadOnly Property Parcial() As String
            Get
                Return ResourceManager.GetString("Parcial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parcialmente.
        '''</summary>
        Public Shared ReadOnly Property Parcialmente() As String
            Get
                Return ResourceManager.GetString("Parcialmente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pasaporte.
        '''</summary>
        Public Shared ReadOnly Property Pasaporte() As String
            Get
                Return ResourceManager.GetString("Pasaporte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pasos:.
        '''</summary>
        Public Shared ReadOnly Property PasosDosPuntos() As String
            Get
                Return ResourceManager.GetString("PasosDosPuntos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pendiente.
        '''</summary>
        Public Shared ReadOnly Property Pendiente() As String
            Get
                Return ResourceManager.GetString("Pendiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permiso.
        '''</summary>
        Public Shared ReadOnly Property Permiso() As String
            Get
                Return ResourceManager.GetString("Permiso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permisos.
        '''</summary>
        Public Shared ReadOnly Property Permisos() As String
            Get
                Return ResourceManager.GetString("Permisos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permisos efectivos.
        '''</summary>
        Public Shared ReadOnly Property PermisosEfectivos() As String
            Get
                Return ResourceManager.GetString("PermisosEfectivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permisos oficinas.
        '''</summary>
        Public Shared ReadOnly Property PermisosOficinas() As String
            Get
                Return ResourceManager.GetString("PermisosOficinas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permutar origen y destino.
        '''</summary>
        Public Shared ReadOnly Property PermutarOrigenYDestino() As String
            Get
                Return ResourceManager.GetString("PermutarOrigenYDestino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pie de página.
        '''</summary>
        Public Shared ReadOnly Property PieDePagina() As String
            Get
                Return ResourceManager.GetString("PieDePagina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Al menos 3 caracteres.
        '''</summary>
        Public Shared ReadOnly Property PlaceHolderAlMenos3Caracteres() As String
            Get
                Return ResourceManager.GetString("PlaceHolderAlMenos3Caracteres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Búsqueda por documento, nombre o identificador.
        '''</summary>
        Public Shared ReadOnly Property PlaceHolderBusquedaCiudadanos() As String
            Get
                Return ResourceManager.GetString("PlaceHolderBusquedaCiudadanos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to por favor.
        '''</summary>
        Public Shared ReadOnly Property porFavor() As String
            Get
                Return ResourceManager.GetString("porFavor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por fila.
        '''</summary>
        Public Shared ReadOnly Property PorFila() As String
            Get
                Return ResourceManager.GetString("PorFila", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por tipo.
        '''</summary>
        Public Shared ReadOnly Property PorTipo() As String
            Get
                Return ResourceManager.GetString("PorTipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predet..
        '''</summary>
        Public Shared ReadOnly Property Predet() As String
            Get
                Return ResourceManager.GetString("Predet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Predeterminado.
        '''</summary>
        Public Shared ReadOnly Property Predeterminado() As String
            Get
                Return ResourceManager.GetString("Predeterminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Principal.
        '''</summary>
        Public Shared ReadOnly Property Principal() As String
            Get
                Return ResourceManager.GetString("Principal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Problema en la autenticación.
        '''</summary>
        Public Shared ReadOnly Property ProblemaEnLaAutenticacion() As String
            Get
                Return ResourceManager.GetString("ProblemaEnLaAutenticacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procedencia.
        '''</summary>
        Public Shared ReadOnly Property Procedencia() As String
            Get
                Return ResourceManager.GetString("Procedencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proceso automático.
        '''</summary>
        Public Shared ReadOnly Property ProcesoAutomatico() As String
            Get
                Return ResourceManager.GetString("ProcesoAutomatico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provincia.
        '''</summary>
        Public Shared ReadOnly Property Provincia() As String
            Get
                Return ResourceManager.GetString("Provincia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provisional.
        '''</summary>
        Public Shared ReadOnly Property Provisional() As String
            Get
                Return ResourceManager.GetString("Provisional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pruebas.
        '''</summary>
        Public Shared ReadOnly Property Pruebas() As String
            Get
                Return ResourceManager.GetString("Pruebas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Razón social.
        '''</summary>
        Public Shared ReadOnly Property RazonSocial() As String
            Get
                Return ResourceManager.GetString("RazonSocial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Razón social o nombre completo.
        '''</summary>
        Public Shared ReadOnly Property RazonSocialNombreCompleto() As String
            Get
                Return ResourceManager.GetString("RazonSocialNombreCompleto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recargar.
        '''</summary>
        Public Shared ReadOnly Property Recargar() As String
            Get
                Return ResourceManager.GetString("Recargar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recargar. Perderá los datos.
        '''</summary>
        Public Shared ReadOnly Property RecargarPerderaLosDatos() As String
            Get
                Return ResourceManager.GetString("RecargarPerderaLosDatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reconocimientos.
        '''</summary>
        Public Shared ReadOnly Property Reconocimientos() As String
            Get
                Return ResourceManager.GetString("Reconocimientos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ref. Procedencia.
        '''</summary>
        Public Shared ReadOnly Property RefProcedencia() As String
            Get
                Return ResourceManager.GetString("RefProcedencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registro.
        '''</summary>
        Public Shared ReadOnly Property Registro() As String
            Get
                Return ResourceManager.GetString("Registro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registro de Entrada.
        '''</summary>
        Public Shared ReadOnly Property RegistroDeEntrada() As String
            Get
                Return ResourceManager.GetString("RegistroDeEntrada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registro de Salida.
        '''</summary>
        Public Shared ReadOnly Property RegistroDeSalida() As String
            Get
                Return ResourceManager.GetString("RegistroDeSalida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reintentar acceso.
        '''</summary>
        Public Shared ReadOnly Property ReintentarAcceso() As String
            Get
                Return ResourceManager.GetString("ReintentarAcceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Representante.
        '''</summary>
        Public Shared ReadOnly Property Representante() As String
            Get
                Return ResourceManager.GetString("Representante", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Representantes.
        '''</summary>
        Public Shared ReadOnly Property Representantes() As String
            Get
                Return ResourceManager.GetString("Representantes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to resultados.
        '''</summary>
        Public Shared ReadOnly Property resultados() As String
            Get
                Return ResourceManager.GetString("resultados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resumen.
        '''</summary>
        Public Shared ReadOnly Property Resumen() As String
            Get
                Return ResourceManager.GetString("Resumen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Salida.
        '''</summary>
        Public Shared ReadOnly Property Salida() As String
            Get
                Return ResourceManager.GetString("Salida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se añadió un {0}. {1}.
        '''</summary>
        Public Shared ReadOnly Property SeAnadioUn() As String
            Get
                Return ResourceManager.GetString("SeAnadioUn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se eliminó un {0} con {1}.
        '''</summary>
        Public Shared ReadOnly Property SeEliminoUn() As String
            Get
                Return ResourceManager.GetString("SeEliminoUn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to segundos.
        '''</summary>
        Public Shared ReadOnly Property segundos() As String
            Get
                Return ResourceManager.GetString("segundos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Seguro que desea continuar?.
        '''</summary>
        Public Shared ReadOnly Property SeguroQueDeseaContinuar() As String
            Get
                Return ResourceManager.GetString("SeguroQueDeseaContinuar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccionado.
        '''</summary>
        Public Shared ReadOnly Property Seleccionado() As String
            Get
                Return ResourceManager.GetString("Seleccionado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccionar.
        '''</summary>
        Public Shared ReadOnly Property Seleccionar() As String
            Get
                Return ResourceManager.GetString("Seleccionar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sencilla.
        '''</summary>
        Public Shared ReadOnly Property Sencilla() As String
            Get
                Return ResourceManager.GetString("Sencilla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sí.
        '''</summary>
        Public Shared ReadOnly Property Si() As String
            Get
                Return ResourceManager.GetString("Si", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to si el tipo de persona es {0}.
        '''</summary>
        Public Shared ReadOnly Property siElTipoDePersonaEs() As String
            Get
                Return ResourceManager.GetString("siElTipoDePersonaEs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alguno de ellos está repetido [{0}].
        '''</summary>
        Public Shared ReadOnly Property SiHayVariosNoDebenEstarRepetidos() As String
            Get
                Return ResourceManager.GetString("SiHayVariosNoDebenEstarRepetidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Algunos de ellos no están definidos.
        '''</summary>
        Public Shared ReadOnly Property SiIndicaUnoDebeEstarDefinido() As String
            Get
                Return ResourceManager.GetString("SiIndicaUnoDebeEstarDefinido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sin cambios.
        '''</summary>
        Public Shared ReadOnly Property SinCambios() As String
            Get
                Return ResourceManager.GetString("SinCambios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sincronizar.
        '''</summary>
        Public Shared ReadOnly Property Sincronizar() As String
            Get
                Return ResourceManager.GetString("Sincronizar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sincronizar ciudadanos.
        '''</summary>
        Public Shared ReadOnly Property SincronizarCiudadanos() As String
            Get
                Return ResourceManager.GetString("SincronizarCiudadanos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sin documento.
        '''</summary>
        Public Shared ReadOnly Property SinDocumento() As String
            Get
                Return ResourceManager.GetString("SinDocumento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si su administrador ha modificado los permisos debe cerrar la sesión, cerrar el navegador y abrir el navegador de nuevo para que se vean reflejados..
        '''</summary>
        Public Shared ReadOnly Property SiSuAdminHaModificadoLosPermisos() As String
            Get
                Return ResourceManager.GetString("SiSuAdminHaModificadoLosPermisos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subir.
        '''</summary>
        Public Shared ReadOnly Property Subir() As String
            Get
                Return ResourceManager.GetString("Subir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subir fichero.
        '''</summary>
        Public Shared ReadOnly Property SubirFichero() As String
            Get
                Return ResourceManager.GetString("SubirFichero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subir ficheros.
        '''</summary>
        Public Shared ReadOnly Property SubirFicheros() As String
            Get
                Return ResourceManager.GetString("SubirFicheros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El tamaño máximo de es de {0} MB.
        '''</summary>
        Public Shared ReadOnly Property TamanoMaximoEs0MB() As String
            Get
                Return ResourceManager.GetString("TamanoMaximoEs0MB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teléfono.
        '''</summary>
        Public Shared ReadOnly Property Telefono() As String
            Get
                Return ResourceManager.GetString("Telefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teléfonos.
        '''</summary>
        Public Shared ReadOnly Property Telefonos() As String
            Get
                Return ResourceManager.GetString("Telefonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Termina.
        '''</summary>
        Public Shared ReadOnly Property Termina() As String
            Get
                Return ResourceManager.GetString("Termina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tiene.
        '''</summary>
        Public Shared ReadOnly Property Tiene() As String
            Get
                Return ResourceManager.GetString("Tiene", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo.
        '''</summary>
        Public Shared ReadOnly Property Tipo() As String
            Get
                Return ResourceManager.GetString("Tipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo de autenticación.
        '''</summary>
        Public Shared ReadOnly Property TipoAutenticacion() As String
            Get
                Return ResourceManager.GetString("TipoAutenticacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo de personalidad.
        '''</summary>
        Public Shared ReadOnly Property TipoDePersonalidad() As String
            Get
                Return ResourceManager.GetString("TipoDePersonalidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo teléfono.
        '''</summary>
        Public Shared ReadOnly Property TipoTelefono() As String
            Get
                Return ResourceManager.GetString("TipoTelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Todos.
        '''</summary>
        Public Shared ReadOnly Property Todos() As String
            Get
                Return ResourceManager.GetString("Todos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unificar.
        '''</summary>
        Public Shared ReadOnly Property Unificar() As String
            Get
                Return ResourceManager.GetString("Unificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unificar ciudadanos.
        '''</summary>
        Public Shared ReadOnly Property UnificarCiudadanos() As String
            Get
                Return ResourceManager.GetString("UnificarCiudadanos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Universidad.
        '''</summary>
        Public Shared ReadOnly Property Universidad() As String
            Get
                Return ResourceManager.GetString("Universidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ver.
        '''</summary>
        Public Shared ReadOnly Property Ver() As String
            Get
                Return ResourceManager.GetString("Ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Versión.
        '''</summary>
        Public Shared ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volver.
        '''</summary>
        Public Shared ReadOnly Property Volver() As String
            Get
                Return ResourceManager.GetString("Volver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volver al índice.
        '''</summary>
        Public Shared ReadOnly Property VolverAlIndice() As String
            Get
                Return ResourceManager.GetString("VolverAlIndice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volver al listado de ciudadanos.
        '''</summary>
        Public Shared ReadOnly Property VolverAlListadoDeCiudadanos() As String
            Get
                Return ResourceManager.GetString("VolverAlListadoDeCiudadanos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volver al modo de subida de ficheros.
        '''</summary>
        Public Shared ReadOnly Property VolverAlModoDeSubidaDeFicheros() As String
            Get
                Return ResourceManager.GetString("VolverAlModoDeSubidaDeFicheros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volver a subir el fichero.
        '''</summary>
        Public Shared ReadOnly Property VolverASubirElFichero() As String
            Get
                Return ResourceManager.GetString("VolverASubirElFichero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Y {0} resultados más.
        '''</summary>
        Public Shared ReadOnly Property YxResultadosMas() As String
            Get
                Return ResourceManager.GetString("YxResultadosMas", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
